apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  namespace: lab3
  annotations:
    volume.beta.kubernetes.io/storage-class: localstorage
spec:
  volumeName: mongo-pv-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
