apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-local
  labels:
    type: local
spec:
  storageClassName: localstorage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mongodb
